Controllers/AnalyzeController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Zoodex.Models;

namespace Zoodex.Controllers
{
    public class AnalyzeController : BaseController
    {
        // GET: Analyze
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Predict()
        {
            using (HttpClient httpClient = new HttpClient())
            {
                HttpPostedFileBase currentFile = Request.Files[0];
                string filePath = Path.Combine(HttpContext.Server.MapPath("~/Storage/Analysis"), currentFile.FileName);
                currentFile.SaveAs(filePath);

                HttpResponseMessage response = await httpClient.GetAsync("https://zoodex-cnn-pm25.onrender.com/predict/" + "https://zoodex.azurewebsites.net/Storage/Analysis/" + currentFile.FileName);

                string responseJson = await response.Content.ReadAsStringAsync();
                Predict predict = JsonConvert.DeserializeObject<Predict>(responseJson);
                predict.Prediction = predict.Prediction.Replace("-", " ");
                using (Context)
                {
                    Reptiles reptile = Context.Reptiles.Where(a => a.Specie.Contains(predict.Prediction)).FirstOrDefault();
                    ViewBag.Reptile = reptile;
                    ViewBag.Confidence = predict.Probability + "%";
                    ViewBag.Image = "https://zoodex.azurewebsites.net/Storage/Analysis/" + currentFile.FileName;
                }

            }
            return View();
        }
    }
}

Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Zoodex.Models;
using static System.Net.WebRequestMethods;

namespace Zoodex.Controllers
{
    public class PostController : BaseController
    {
        public ActionResult Create()
        {
            if (Session["User"] != null)
            {
                return View();
            }

            return RedirectToAction("Index", "Home");
        }

        public ActionResult View(int Id)
        {
            if (Session["User"] != null)
            {
                ViewBag.Post = GetPost(Id);
                return View();
            }

            return RedirectToAction("Index", "Home");
        }
        [HttpPost]
        public ActionResult CreatePost()
        {
            Users user = (Users)Session["User"];
            Posts post = new Posts();
            Files file = new Files();
            string title = Request.Form["title"];
            string content = Request.Form["content"];
           
            try
            {
                
                using(Context)
                {
                    post = Context.Posts.OrderByDescending(a => a.PKPostID).FirstOrDefault();

                    HttpPostedFileBase currentFile = Request.Files[0];
                    string fileName = post == null ? "Post_1_Image." + currentFile.FileName.Split('.')[1] : "Post_" + post.PKPostID + "_Image." + currentFile.FileName.Split('.')[1];
                    string filePath = Path.Combine(HttpContext.Server.MapPath("~/Storage/Posts"), fileName);
                    currentFile.SaveAs(filePath);

                    Context.Files.Add(new Files
                    {
                        FileName = fileName,
                        Path = "https://zoodex.azurewebsites.net/Storage/Posts/" + fileName,
                        FKUpdatedBy = user.PKUserID,
                        LastUpdated = DateTime.Now,
                        Deleted = false
                    });

                    Context.SaveChanges();

                    file = Context.Files.Where(a => a.FileName == fileName && a.Deleted == false).FirstOrDefault();

                    Context.Posts.Add(new Posts
                    {
                        Title = title,
                        Content = content,
                        FKPicture = file.PKFileID,
                        FKUpdatedBy = user.PKUserID,
                        LastUpdated = DateTime.Now,
                        Deleted = false
                    });

                    Context.SaveChanges();
                    WriteLog(user.PKUserID, 1, "Post Created!");
                    TempData["Success"] = "Post Created!";
                }
            }
            catch (Exception e)
            {
                user = user != null ? user : new Users();
                TempData["Errors"] = e.Message;
                WriteLog(user.PKUserID, 0, "In CreatePost: " + e.Message);
            }
            return RedirectToAction("Index", "Home");
        }

        public List<PostModel> GetPosts(Users user)
        {
            List<Posts> posts = new List<Posts>();
            List<PostModel> PostList = new List<PostModel>();
            try
            {
                using (Context)
                {
                    posts = Context.Posts.Where(a => a.Deleted == false).OrderByDescending(a => a.PKPostID).ToList();
                    foreach(Posts post in posts)
                    {
                        Users PostedBy = Context.Users.Where(a => a.PKUserID == post.FKUpdatedBy).FirstOrDefault();
                        Files Image = Context.Files.Where(a => a.PKFileID == post.FKPicture).FirstOrDefault();
                        PostList.Add(new PostModel
                        {
                            Id = post.PKPostID,
                            Title = post.Title,
                            PostedById = PostedBy.PKUserID,
                            ProfileImageId = PostedBy.FKProfilePicture,
                            PostedBy = PostedBy.GetFullName(),
                            Image = Image.Path,
                            Content = post.Content,
                            Created = post.LastUpdated,
                            Deleted = false
                        });
                    }
                }
            }
            catch (Exception e)
            {
                TempData["Errors"] = e.Message;
                WriteLog(user.PKUserID, 0, "In GetPosts: " + e.Message);
            }

            return PostList;
        }

        public PostModel GetPost(int Id)
        {
            Users user = (Users)Session["User"];
            Posts post = new Posts();
            PostModel PostModel = new PostModel();
            try
            {
                using (Context)
                {
                    post = Context.Posts.Where(a => a.PKPostID == Id && a.Deleted == false).FirstOrDefault();
                    Users PostedBy = Context.Users.Where(a => a.PKUserID == post.FKUpdatedBy).FirstOrDefault();
                    Files Image = Context.Files.Where(a => a.PKFileID == post.FKPicture).FirstOrDefault();
                    PostModel.Id = post.PKPostID;
                    PostModel.Title = post.Title;
                    PostModel.PostedById = PostedBy.PKUserID;
                    PostModel.PostedBy = PostedBy.GetFullName();
                    PostModel.ProfileImageId = PostedBy.FKProfilePicture;
                    PostModel.Image = Image.Path;
                    PostModel.Content = post.Content;
                    PostModel.Created = post.LastUpdated;
                    PostModel.Deleted = false;
                }
            }
            catch (Exception e)
            {
                TempData["Errors"] = e.Message;
                WriteLog(user.PKUserID, 0, "In GetPost: " + e.Message);
            }

            return PostModel;
        }
    }
}

Views/Shared/_Layout.cshtml
@using Zoodex.Models
@using Zoodex.Functions
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Zoodex</title>
    <link href="~/Content/Site.css" type="text/css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" type="text/css" rel="stylesheet" />
    <link href="~/Content/all.min.css" type="text/css" rel="stylesheet" />
    <link href="~/Content/dataTables.bootstrap5.min.css" type="text/css" rel="stylesheet" />
    <link href="~/Content/Toast.css" type="text/css" rel="stylesheet" />
</head>
<body>
    <header>
        @{ Users user = (Users)Session["User"]; }
        <nav class="navbar navbar-expand-lg navbar-dark bg-green fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" href="@Url.Action("Index","Home")">
                    <img src="~/favicon.ico" alt="home" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#menu" aria-controls="menu" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="menu">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" href="@Url.Action("Index", "Home")">
                                <i class="fa-solid fa-home-alt"></i> Home
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="@Url.Action("About", "Home")">
                                <i class="fa-solid fa-people-group"></i> About Us
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="@Url.Action("FAQ", "Home")">
                                <i class="fa-solid fa-question"></i> FAQ
                            </a>
                        </li>
                        @if (user != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link active" href="@Url.Action("Index", "Reptiles")">
                                    <i class="fa-solid fa-staff-aesculapius"></i> Reptiles
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" href="@Url.Action("Index", "Analyze")">
                                    <i class="fa-solid fa-magnifying-glass-chart"></i> Analyze
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" href="@Url.Action("Create", "Post")">
                                    <i class="fa-solid fa-blog"></i> Create Post
                                </a>
                            </li>
                            if (RoleHandler.GetRole(user.PKUserID) == "Admin")
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle active" id="adminDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        <i class="fa-solid fa-lock"></i> Admin
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="adminDropdown">
                                        <li class="nav-item">
                                            <a class="dropdown-item" href="@Url.Action("Logs", "Admin")">
                                                <i class="fa-solid fa-clipboard-list"></i> Logs
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <hr class="dropdown-divider">
                                        </li>
                                        <li class="nav-item">
                                            <a class="dropdown-item" href="@Url.Action("Database", "Admin")">
                                                <i class="fa-solid fa-database"></i> Database
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                            }
                        }
                    </ul>
                    <ul class="navbar-nav ms-auto">
                        @if (user != null)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle active" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <img src="@Path.Combine(HttpContext.Current.Request.Url.GetLeftPart(UriPartial.Authority),ImageHandler.GetProfilePicture(user.FKProfilePicture))" alt="Profile picture" class="profile-picture rounded-circle"> <span class="ms-2">@user.GetFullName()</span>
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="userDropdown">
                                    <li class="nav-item">
                                        <a class="dropdown-item" href="@Url.Action("Profile", "User")">
                                            <i class="fa-solid fa-user-gear"></i> Profile
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" href="@Url.Action("Exit", "Access")">
                                            <i class="fa-solid fa-arrow-right-from-bracket"></i> Log Out
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link active" href="@Url.Action("Index", "Access")">
                                    <i class="fa-solid fa-arrow-right-to-bracket"></i> Log In
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main>
        @RenderBody()
    </main>
    <footer>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <span class="navbar-text mx-auto">&copy; Zoodex @DateTime.Now.Year</span>
            </div>
        </nav>
    </footer>
    <script src="~/Scripts/jquery-3.6.0.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate.min.js" type="text/javascript"></script>
    <script src="~/Scripts/modernizr-2.8.3.js" type="text/javascript"></script>
    <script src="~/Scripts/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="~/Scripts/dataTables.bootstrap5.min.js" type="text/javascript"></script>
    <script src="~/Scripts/Toast.js" type="text/javascript"></script>

    @RenderSection("scripts", required: false)
</body>
</html>